FROM alpine:latest

RUN apk add --update go git

ENV GOPATH /go
ENV CGO_ENABLED=0
ENV GO111MODULE=off

RUN mkdir -p /go/src/main
ADD . /go/src/main
RUN go get github.com/prometheus/client_golang/prometheus/promhttp
RUN go get github.com/prometheus/client_golang/prometheus
RUN go get github.com/Infonair/go-xen-api-client
RUN go get gopkg.in/yaml.v2
#RUN go mod download github.com/prometheus/client_golang/prometheus

RUN cd /go/src/main && go build -o /bin/xapi_exporter .

CMD /bin/cat
